-- 실습 11-1
CREATE TABLE DEPT_TCL
    AS SELECT *
         FROM DEPT;

SELECT * FROM DEPT_TCL;

-- 실습 11-2
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

-- 실습 11-3
ROLLBACK;

SELECT * FROM DEPT_TCL;

-- 실습 11-4
INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

SELECT * FROM DEPT_TCL;

-- 실습 11-5
COMMIT;

-- 실습 11-6
SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-7
DELETE FROM DEPT_TCL
 WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-8
COMMIT;

SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-9
SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-10
UPDATE DEPT_TCL SET LOC='SEOUL'
 WHERE DEPTNO = 30;

SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-11
UPDATE DEPT_TCL SET DNAME='DATABASE'
 WHERE DEPTNO = 30;

-- 실습 11-12
COMMIT;

SELECT * FROM EMP_TEMP;

-- 실습 11-13
SELECT * FROM DEPT_TCL;

SELECT * FROM DEPT_TCL;

-- 실습 11-14
COMMIT;

-- 실습 11-15
SELECT * FROM DEPT_TCL;


-- EX001

```
① 세션 A : DNAME은 DATABASE, LOC은 SEOUL /
  세션 B : DNAME은 SALES, LOC은 CHICAGO

② 세션 B의 UPDATE 명령이 실행된 후 대기상태(HANG)가 된다. 세션 A의 트랜잭션이
아직 종료되지 않았기 때문이다.

③ 세션 A의 ROLLBACK 명령이 실행되자마자 세션 B의 UPDATE문이 수행된다. 세션 A
의 트랜잭션에 의한 행 레벨 록이 끝났기 때문이다.

④ 세션 A : DNAME은 SALES, LOC은 CHICAGO
  세션 B : DNAME은 DATABASE, LOC은 SEOUL

⑤ 세션 A : DNAME은 DATABASE, LOC은 SEOUL
  세션 B : DNAME은 DATABASE, LOC은 SEOUL
```